**E-commerce Sales Analysis**

**Objective:**

Analyze sales data to identify trends and improve business performance.

***Import Libraries***

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

***Load Dataset***

In [ ]:
df = pd.read_csv('Superstore.csv')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

***Data Understanding***

In [ ]:
# Check columns
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [ ]:
# Check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9653 entries, 0 to 9652
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9653 non-null   int64
 1   Order ID       9653 non-null   object
 2   Order Date     9653 non-null   object
 3   Ship Date      9653 non-null   object
 4   Ship Mode      9653 non-null   object
 5   Customer ID    9653 non-null   object
 6   Customer Name  9653 non-null   object
 7   Segment        9653 non-null   object
 8   Country        9653 non-null   object
 9   City           9653 non-null   object
 10  State          9653 non-null   object
 11  Postal Code    9643 non-null   float64
 12  Region         9652 non-null   object
 13  Product ID     9652 non-null   object
 14  Category       9652 non-null   object
 15  Sub-Category   9652 non-null   object
 16  Product Name   9652 non-null   object
 17  Sales          9652 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
# Explore structure
df.describe()

            Row ID   Postal Code         Sales
count  9653.000000   9643.000000   9652.000000
mean   4827.000000  55254.238100    230.536565
std    2786.725408  32010.600461    628.096002
min       1.000000   1040.000000      0.444000
25%    2414.000000  23223.000000     17.295000
50%    4827.000000  57103.000000     54.384000
75%    7240.000000  90004.000000    209.970000
max    9653.000000  99301.000000  22638.480000

**Data Cleaning**

In [ ]:
# Total of nulls
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      10
Region            1
Product ID        1
Category          1
Sub-Category      1
Product Name      1
Sales             1
dtype: int64

A check for missing values revealed that all columns are complete except for the "Postal Code" column, which contains 11 missing entries. This indicates that the dataset is largely clean, with only a minor issue in one column that requires handling.

In [ ]:
# Handling null values in Postal Code column
df['Postal Code'] = df['Postal Code'].fillna(df['Postal Code'].mean())

# Checking another time
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           1
Product ID       1
Category         1
Sub-Category     1
Product Name     1
Sales            1
dtype: int64

The missing values in the "Postal Code" column were handled using mean imputation to preserve the dataset's completeness without removing any records.

After applying this method, a verification step confirmed that all missing values were successfully resolved, resulting in a fully complete dataset ready for analysis.

In [ ]:
# Total of duplicates
df[df.duplicated()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales]
Index: []

A check for duplicate records was performed, and no duplicate entries were found in the dataset.

This indicates that the data is consistent and does not require any further deduplication, ensuring the reliability of the analysis.

***Analysis***

In [ ]:
# Total Revenue
total_revenue = df['Sales'].sum()
print('Total revenue is : ',total_revenue)

Total revenue is :  2225138.9235

# The total revenue generated is approximately $2.26 million, indicating a strong overall sales performance and a solid market presence.

In [ ]:
# Sales by Category
df.groupby('Category')['Sales'].sum().sort_values(ascending= False)

Category
Technology         817017.4530
Furniture          715181.8625
Office Supplies    692939.6080
Name: Sales, dtype: float64

The Technology category is the top-performing category in terms of total sales, indicating strong customer demand for technology-related products and making it a key revenue driver for the business.

In [ ]:
# Sales by Sub-Category
df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending= False)

Sub-Category
Phones         318878.9000
Chairs         317902.8410
Storage        215174.3200
Tables         202083.3600
Binders        194692.2130
Machines       189238.6310
Accessories    162651.8280
Copiers        146248.0940
Bookcases      107431.0475
Appliances     103933.8370
Furnishings     87764.6140
Paper           76142.1460
Supplies        46163.1880
Art             26446.8860
Envelopes       15655.1920
Labels          11733.4860
Fasteners        2998.3400
Name: Sales, dtype: float64

At a more detailed level, sub-categories such as Phones and Chairs generate the highest sales, highlighting them as the primary contributors to revenue.

In contrast, sub-categories like Fasteners, Labels, and Envelopes show significantly lower sales, indicating potential underperformance or lower demand in these product areas.

In [ ]:
# Sales by Region
df.groupby('Region')['Sales'].sum()

Region
Central    484945.9640
East       655668.7820
South      385511.5370
West       699012.6405
Name: Sales, dtype: float64

The West region generates the highest sales, followed by the East region, indicating that these areas are the strongest markets for the business.

In contrast, the South region shows the lowest performance, suggesting potential opportunities for growth and market expansion.

In [ ]:
# Top Customers
df.groupby('Customer Name')['Sales'].sum().sort_values(ascending = False).head(10)

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14588.580
Adrian Barton         14473.571
Ken Lonsdale          14153.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

A small group of customers contributes significantly to total revenue, with top customers such as Sean Miller and Tamara Chand generating the highest sales.

This indicates the presence of high-value customers who play a crucial role in driving overall business performance.

In [ ]:
# Yearly Trend
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['year'] = df['Order Date'].dt.year
df.groupby('year')['Sales'].sum()

year
2015    470043.8881
2016    451919.2562
2017    589481.1380
2018    713694.6412
Name: Sales, dtype: float64

Sales show an overall upward trend over the years, despite a slight decline in 2016.
Growth becomes significant from 2017 onwards, reaching the highest level in 2018, which indicates strong business expansion and improved performance.

The date column was parsed using day-first format to ensure correct datetime conversion.

In [ ]:
# Shipping Analysis

df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)
df['delivery_days'] = (df['Ship Date'] - df['Order Date']).dt.days
df['delivery_days'].mean()

np.float64(3.9588728892572256)

The average delivery time is approximately 4 days, indicating an efficient shipping process.

However, further optimization could enhance customer satisfaction and provide a competitive advantage.

In [ ]:
# Sales by Segment
df.groupby('Segment')['Sales'].sum()

Segment
Consumer       1.130280e+06
Corporate      6.770334e+05
Home Office    4.178254e+05
Name: Sales, dtype: float64

The Consumer segment generates the highest share of sales, significantly outperforming Corporate and Home Office segments.

This suggests that individual customers are the primary drivers of revenue for the business

***Recommandations***

T*hese recommendations are based on the analysis of sales performance, customer behavior, and regional trends.*

- Increase overall revenue by focusing on high-performing products and regions while optimizing pricing and promotion strategies.

- Prioritize the Technology category by increasing marketing efforts and product availability, as it is the main driver of revenue.

- Focus on top-performing sub-categories such as Phones and Chairs by promoting them further and ensuring consistent stock levels.

- Strengthen business operations in high-performing regions like the West and East, while developing targeted strategies to improve sales in underperforming regions such as the South.

- Implement customer retention strategies for high-value customers (e.g., loyalty programs, exclusive offers) to maintain and grow their contribution to revenue.

- Leverage seasonal trends by increasing promotions and inventory during peak months (November and December), and introducing campaigns to boost sales during low-performing months.

- Optimize logistics and delivery processes to reduce shipping time and enhance overall customer satisfaction.

- Continue focusing on the Consumer segment while exploring opportunities to grow Corporate and Home Office segments through tailored marketing strategies and business-oriented offers.

***Export data***

In [ ]:
df.to_csv("cleaned_superstore.csv", index=False)